### PR TITLE
Remove color support from "Include" filter.

### PR DESCRIPTION
**Pull request by Ishmaeel**
I would very much like to use the "include" filter but the fact that it has precedence over dynamic process colors has been a deal breaker.

Now include filter does not apply text coloring either, very much like the exclude filter. Not a big functionality loss because it is still possible to recolor included lines by defining an additional highlight rule. Perhaps more work, but definitely more flexibility.

Accept PR if it makes sense. Reject if not compatible with project vision.

### CODE REVIEW

**Comment by janwilmans** [comment]
thanks for the suggestion, I can see your point, you mean that if you use the include filter, it will apply its color to the included line, and overwrite the 'process color' ?

**Comment by Ishmaeel** [comment]
Yes, process coloring stops working as soon as an *include* filter is added.

**Comment by janwilmans** [comment]
Thanks for the suggestion, I will have another look at feature requests.

**Comment by janwilmans** [comment]
I think you suggestion is good, thank you for the contribution!

**Pull request merged**
